### ISSUE TITLE
[xfce] using the default Menda theme some black icons you can't see

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/artwork-maia#2]
In the following screen shot you can see the issue:

![maia-xfce-dark](https://cloud.githubusercontent.com/assets/5050022/6996274/1d9b0566-db7e-11e4-965c-c7a4386e8960.png)

Unmounted medias (hard disks) or the network/volume icon you can't see. Also the default pamac tray icon sometimes is not so visible. If we want to use it for XFCE, we might need some enhancements ...

**Comment by mcder3** [comment]
Icons are made under the scheme of plasma 5 is why muetra this error.

would have to make an additional version xfce

**Comment by philmmanjaro** [comment]
Ah ok. Then we have to think about that ... Thx for verfying it.

**Comment by mcder3** [comment]
Now the icons should be compatible with XFCE

**Comment by philmmanjaro** [comment]
Well, much better David but I recommend to copy over some icons from **Menda** theme. Logout and Clipboard you can't see. Also in the menus some you just see with overlay. Don't know how it will affect plasma theme if we change them too ...

Menda:
![menda](https://cloud.githubusercontent.com/assets/5050022/7017040/57e0d920-dcf1-11e4-915f-f9c8eaa3d1f3.jpg) 

Maia:
![maia](https://cloud.githubusercontent.com/assets/5050022/7017043/5ce9f9b0-dcf1-11e4-8ca1-10791bb2ce61.jpg)

**Comment by mcder3** [comment]
then we have to create a branch, since these icons are housed in the actions folder.

I will try to work during the week with that fork.

 

De: Philip Müller [mailto:notifications@github.com] 
Enviado el: lunes, 06 de abril de 2015 10:44 p.m.
Para: manjaro/artwork-maia
CC: David Linares
Asunto: Re: [artwork-maia] [xfce] using the default Menda theme some black icons you can't see (#2)

 

Well, much better David but I recommend to copy over some icons from Menda theme. Logout and Clipboard you can't see. Also in the menus some you just see with overlay. Don't know how it will affect plasma theme if we change them too ...

Menda:
 <https://cloud.githubusercontent.com/assets/5050022/7017040/57e0d920-dcf1-11e4-915f-f9c8eaa3d1f3.jpg> 

Maia:
 <https://cloud.githubusercontent.com/assets/5050022/7017043/5ce9f9b0-dcf1-11e4-8ca1-10791bb2ce61.jpg>

**Comment by philmmanjaro** [comment]
icons-xfce does it. thx. keep it up ;)

**Comment by philmmanjaro** [comment]
Seems now **icons-xfce/status/** makes some issues. Speaker icons and pamac for example should be gray-ish.

**Comment by mcder3** [comment]
Fix status icons.

![workspace 1_001](https://cloud.githubusercontent.com/assets/1154298/7137898/062f5c8a-e27a-11e4-8d1c-bf816e776935.png)
